### ISSUE TITLE
Evaluate locations for first meet up

### ISSUE THREAD

**Issue by jnbt** [ElixirRuhr/orga#2]
We need to at least have a short evaluation of possible locations for the first meet up

**Comment by solidnerd** [comment]
[BermudaHaus](http://bermudahaus.de) 15€ per Hour for a meeting room.

**Comment by schnittchen** [comment]
Do we have attendance estimates?

das-labor.org would be possible as well, if it's roughly <50 heads

**Comment by renao** [comment]
Any restrictions? Bochum-first? Size?

**Comment by solidnerd** [comment]
@schnittchen  We could assume that max 20 people participate. This is the current adjustment of the [Meetup](http://www.meetup.com/de/ElixirRuhr/events/226415527/) .

**Comment by jnbt** [comment]
Does somebody could provide a beamer? Otherwise we must choose a location providing one, or rent it.

**Comment by JanOwiesniak** [comment]
@SolidNerd Meetup limit is set to 20 people because i picked a random number between 20-50. The limit is still open for discussion. Depends on the possible locations.

@renao I would prefer Bochum. If it's possible.

@schnittchen 'das-labor' sounds great. A small bar would be nice too. I think Café Konkret even has a beamer.

**Comment by splattael** [comment]
As @schnittchen said "das labor" provides all goodies for a meet-up! Beamer, bar, nerdish atmosphere. It's the best (and probably cheapest) location for a start I think.

**Comment by jnbt** [comment]
@schnittchen do you have some active contact there? Some time has passed since my last "labor" visit.

**Comment by schnittchen** [comment]
Sure! Do we have a rough idea when to have the meetup? I'll try to schedule then.

**Comment by JanOwiesniak** [comment]
I would suggest to schedule it in the first quarter of the next year.

**Comment by renao** [comment]
Shall we schedule it here or should we open another issue for that?

What about the first week in February? Let's get things started in here, I assume there'll be some spare time in the next weeks for that.

**Comment by jnbt** [comment]
I agree. 

@schnittchen could you please be so kind and ask "das labor" regarding the first week of February?

**Comment by schnittchen** [comment]
Looks like Tuesday and Friday are already taken: https://www.das-labor.org/wiki/Kalender/Wiki

I will check back and lock the respective day when we can agree on one, just ping me.

**Comment by solidnerd** [comment]
Any updates in this ? If not i would suggest Thursday (4.2.2016). Starting at 18:30 or later ?

**Comment by rrrene** [comment]
I'm a practicing "Nicht-Karnevalist", but isn't there Karneval right around that date? Does that matter?

**Comment by schnittchen** [comment]
I've added the suggested date here https://www.das-labor.org/wiki/Erstes_ElixirRuhr_Meetup

I guess it will show up here shortly https://www.das-labor.org/wiki/Kalender/Wiki

**Comment by splattael** [comment]
@rrrene "Rosenmontag" is on Feb 8th. And no, I think it does not matter :neckbeard:

**Comment by c-rack** [comment]
There is "Weiberfastnacht" at this date. And yes, it does matter, at least I am not available at this date. A week later would be appreciated.

**Comment by splattael** [comment]
@c-rack Oops, sorry for that. Have fun! :tada:

Let's find another date then. Week later seems fine.

**Comment by schnittchen** [comment]
Is Feb 11 ok with everybody?

**Comment by solidnerd** [comment]
:+1: It's okay for me.
.

**Comment by rrrene** [comment]
:+1:

**Comment by JanOwiesniak** [comment]
Works for me too

**Comment by jnbt** [comment]
+1

**Comment by schnittchen** [comment]
Officially scheduled! Can somebody tweet an early announcement?

**Comment by renao** [comment]
Sounds great.

I guess some drinks are available at the Labor. What about the techy stuff? Beamer, adaptors, cables etc. are there?

**Comment by schnittchen** [comment]
Connectivity to the speaker's laptop should be covered, bringing a spare adapter probably does not hurt however. Drinks are available, caffeine in various forms as well as several kinds of soft drinks.

**Comment by jnbt** [comment]
I suggest to update our homepage and Meetup page before announcing. I can do this task next week (mon / tue).

**Comment by JanOwiesniak** [comment]
@schnittchen is there any limitation of the amount of people for this place?

**Comment by schnittchen** [comment]
roughly <50 heads

**Comment by jnbt** [comment]
OK. Meetup page is updated.
