### ISSUE TITLE
Speakers for first meet up

### ISSUE THREAD

**Issue by jnbt** [ElixirRuhr/orga#3]
- Currently we have a confirmation from @rrrene 
- We should have a second talk

**Comment by schnittchen** [comment]
What's @rrrene's topic?

**Comment by rrrene** [comment]
Not set yet, but we toyed around with the idea of an **"Tooling in Elixir"** talk. 

Aspects would be `elixirc`, Mix, Ecto, Phoenix and possibly [Credo](https://github.com/rrrene/credo), with a focus on the care that goes into the information these tools provide (even when throwing error messages).

**Comment by renao** [comment]
I suppose that we have 2+ talks?

Just some unfinished thoughts from my drive home:

It is a small, young and growing community and I assume that there are not plenty of (quality) speakers right now. We could use this to break through Elixirs borders by adding talks that are not Elixir focused.

With a small format like "#{some} minutes outside the ex" we could add related topics like docker (@SolidNerd?), internet-/server basics etc..

Just to expand one's horizon ;-)

**Comment by jnbt** [comment]
I've got a confirmation from @c-rack. He suggested to give a talk about c-rack/quantum-elixir or jerlang/jerlang. But he is also open for other topics.

As soon I managed to get a introduction about him ready we can post it.

**Comment by schnittchen** [comment]
Sounds like somebody with deep OTP experience, that's very welcome! However, maybe a bit too heavy for a start :)

**Comment by c-rack** [comment]
May I suggest to open another issue like "Ideas for talks" or similar? Currently I have no idea which topics would attract people to attend the meetup...

Also, how long are talks expected to be?

**Comment by schnittchen** [comment]
I bet people would like to see phoenix in action.

**Comment by renao** [comment]
Just to be sure:
the speakers for the first meetup in February are confirmed, also with the date?

**Comment by c-rack** [comment]
As far as I am concerned, yes. Just need to think about a proper topic :smile:

**Comment by rrrene** [comment]
:+1: me too

@jnbt any idea how long our talks should be?

**Comment by jnbt** [comment]
I would prefer not-so-long-talks about 15 - 20 minutes + QA.

**Comment by renao** [comment]
Sounds good, I'd like that, too.
In my opinion it would be nice if the all the talks + QAs would be <= 60 minutes?

So there will be enough spare time after all for interaction, networking etc. pp and everything won't be that strict dictated by comittee.

**Comment by JanOwiesniak** [comment]
I think this issue can be closed for now. All agreed upon that @rrrene and @c-rack are our two speakers. This is what it was all about.

If you want to discuss about the topics please take a look here: https://github.com/ElixirRuhr/orga/issues/4
