### ISSUE TITLE
Talk topics/ideas

### ISSUE THREAD

**Issue by rrrene** [ElixirRuhr/orga#4]
Let's discuss specific talking points here (as mentioned [here](https://github.com/ElixirRuhr/orga/issues/3#issuecomment-160767967)).

The idea for my talk is to be titled "**Good tooling educates**". It would cover ways in which tools can not only be productive assistants, but also be helpful mentors during ones personal "learning phase" with a new language or framework (and how Elixir, Mix, Phoenix get this extremly right).

Other interesting Elixir-related topics could be Phoenix in Action, as mentioned by @schnittchen, or a comparison of Elixir tools like quantum with their traditional counterparts (i.e. cronjobs).

Any ideas?

**Comment by schnittchen** [comment]
I propose a talk about OTP principles (GenServer in particular), which I am going to give soon :)

**Comment by JanOwiesniak** [comment]
Any ideas what your topic will be about @c-rack?

We would like to update the meetup page and the website before we announce the first meetup via social media.
