### ISSUE TITLE
Update Meetup Page

### ISSUE THREAD

**Issue by solidnerd** [ElixirRuhr/orga#5]
[Meetup](http://www.meetup.com/de/ElixirRuhr/events/226415527/) Should provide more informations, like date and place :)

**Comment by solidnerd** [comment]
@JanOwiesniak

**Comment by JanOwiesniak** [comment]
Will so it tomorrow.

**Comment by JanOwiesniak** [comment]
I created a raw draft of the 1st meetup and will publish it at the end of the day.

@jnbt let us take a short look over the draft together

**Comment by jnbt** [comment]
Updated
