### ISSUE TITLE
Social Media Announcement

### ISSUE THREAD

**Issue by JanOwiesniak** [ElixirRuhr/orga#6]
_Channels_
- Twitter
- ElixirStatus
- Meetup
- Lanyrd ?
- Speakerdeck ?
- Anything else?

_Time / Day_

Any suggestions what time / day would be appropriate to get the best reach?

_Message_

Any ideas how to put venue and speaker information into 140 chars?

**Comment by schnittchen** [comment]
negative exponential backoff: two weeks before, several days before, the night before. and an early announcement today or tomorrow can't hurt

**Comment by rrrene** [comment]
I agree with @schnittchen!

Side note: While we could post it to [ElixirStatus](http://elixirstatus.com) in the regular way, we can also use the elixirstatus Twitter account to link the Meetup page directly or to retweet ElixirRuhr related tweets by all of us (meaning that I could, e.g. tweet "Yay, come watch my talk on Elixir tooling and Credo" and then elixirstatus retweets that).

Ideas?

**Comment by jnbt** [comment]
Proposal for Twitter:

> 001 - Where to start? Join our first meet up on 11th Feb 2016. Talks by @rrrene and @ConstantinRack. Details at: http://elixir.ruhr

Time: Always in the morning

**Comment by splattael** [comment]
We should add hash tags. At least: #myelixirstatus

**Comment by jnbt** [comment]
> Starting our first meet up on 11th Feb 2016. Talks by @rrrene and @ConstantinRack. Details at: http://elixir.ruhr #myelixirstatus

**Comment by rrrene** [comment]
+1 for "always in the morning"!

my take:

> Elixir NRW meetup on Feb 11th. Speakers: @rrrene (credo) / @ConstantinRack (quantum). Talk details: http://elixir.ruhr #myelixirstatus

**Comment by splattael** [comment]
:+1:

**Comment by JanOwiesniak** [comment]
I like both. Let's decide and tweet it.

**Comment by schnittchen** [comment]
I prefer the first.

**Comment by c-rack** [comment]
FYI: I have sent a mail to elixir.radar@plataformatec.com.br asking to include the first elixir.ruhr meetup in next elixir.radar newsletter :smile:

**Comment by JanOwiesniak** [comment]
Done. Please retweet.
