### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by JanOwiesniak** [ElixirRuhr/orga#7]
First of all, big thanks to @schnittchen for the free venue!

I would like to sponsor a few free drinks.

Anybody who would like to give a few bucks for some small things to eat?
Probalby a couple of Pizza's?

**Comment by schnittchen** [comment]
Soft drinks are available at the venue.

**Comment by jnbt** [comment]
I think Neopoly could do some sponsoring

**Comment by schnittchen** [comment]
9elements is willing to, as well. The question is, what do we want or need?

**Comment by JanOwiesniak** [comment]
Drinks & Food

**Comment by schnittchen** [comment]
There is a large variety of soft drinks at @das-labor. We could cover these, provided somebody keeps track of the amount that was handed out. (And I need to check back with @9elements, but I believe that's only a formality). @das-labor does not usually sell alcoholic bevs, though.

**Comment by jnbt** [comment]
Perhaps we can order some "Butterbrote" at the http://butterbrotbar.de

**Comment by JanOwiesniak** [comment]
@jnbt +1 for Butterbrotbar
@schnittchen would it be ok if i organize a few beer or is this not appropriate for the location?

**Comment by jnbt** [comment]
@schnittchen Could you get in touch with the "Labor" to figure out how we could organize the drinks? (Would it be sufficient if someone from our team counts the drinks? Can we bring some beer?)

I've reached for the Butterbrotbar and got the following quotation: around 0.75€ per piece. Suggested 3-6 pieces per person. (3 = "It's a snack", 6 = "A full meal"). My suggestion would be 4 per person, resulting in `4 * 50 * 0.75€ = 150€` as max. costs.

They offer a lot of stuff but I suggest the following combination: Mixed small "Butterbrot"-Canapé (options for vegan) and pancake rolls as finger food.

I'll check with the company to sponsor this.

**Comment by schnittchen** [comment]
@JanOwiesniak @jnbt Somebody counting the drinks should suffice, we might even keep a "Strichliste" besides the counter. Just so that we know what expenses we need to refund the Labor.

Bringing a few crates of Beer is no problem for the Labor. The just can't sell that themselves.

I'm curious about the Butterbrote, sounds interesting!

**Comment by jnbt** [comment]
Hi @schnittchen can you confirm the sponsorship for the drinks?. If so we should post a logo to our webpage.

I will update you all about the "butterbrotbar" soon.

**Comment by schnittchen** [comment]
@jnbt sorry for the delay. sponsorship confirmed!

**Comment by jnbt** [comment]
I can now confirm that Neopoly is sponsoring the "Butterbrote". I'll announce the sponsorships soon.

@schnittchen  can you provide a 9elements logo file for the sponsorship

**Comment by schnittchen** [comment]
![9elements_signature_black](https://cloud.githubusercontent.com/assets/166765/12785626/9f4c4648-ca8d-11e5-916f-93317ab49341.png)
 Does this work?

**Comment by jnbt** [comment]
Perfect. Just added it to the page. Preview http://gh-pages-pr-3.preview.elixir.ruhr

**Comment by schnittchen** [comment]
Looks nice
